name: CI-CD

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: coinalertapp-baekhun
  CODE_DEPLOY_APPLICATION_NAME: CoinAlertApp-CodeDeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: CoinAlertApp-CodeDeploy-Group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash


      - name: CodeDeploy
        run: |
          aws deploy create_deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \